### ISSUE TITLE
Support for Hot Water

### ISSUE THREAD

**Issue by LewisSpring** [stringbean/homebridge-drayton-wiser#6]
Hi there. I've just set up my Wiser HubR and so far it seems to work fine!
I've noticed there is not a way to call for Hot Water.
Is this possible for you to implement?

Thanks!

**Comment by sacheenganatra** [comment]
Second this request. Hot water control, especially boost control, would be awesome if its possible.

**Comment by timbojoeNBD** [comment]
I third this too - keen to help, but don't know how.

**Comment by LewisSpring** [comment]
Not sure on the state of this issue - The project seems abandoned and I no longer use this plugin, nor Homebridge.
Closing for no progress.
